const
  ACTION_FAILED = "ACTION_FAILED",
  SET_LOADING = "SET_LOADING",
  UPDATE_SEARCH = "UPDATE_SEARCH",
  FETCH_MOVIE = "FETCH_MOVIE",
  SET_MOVIES_TO_STORE = "SET_MOVIE_TO_STORE",
  SET_ERROR_TO_STORE = "SET_ERROR_TO_STORE",
  SHOW_MOVIE_DETAILS = "SHOW_MOVIE_DETAILS",
  SET_SELECTED_MOVIE = "SET_SELECTED_MOVIE",
  CLEAR_SEARCH = "CLEAR_SEARCH";

export default {
  SET_LOADING,
  ACTION_FAILED,
  UPDATE_SEARCH,
  CLEAR_SEARCH,
  FETCH_MOVIE,
  SET_ERROR_TO_STORE,
  SET_MOVIES_TO_STORE,
  SET_SELECTED_MOVIE,
  SHOW_MOVIE_DETAILS
};
