const
  ACTION_FAILED = "ACTION_FAILED",
  SET_LOADING = "SET_LOADING",
  UPDATE_SEARCH = "UPDATE_SEARCH",
  FETCH_MOVIES = "FETCH_MOVIES",
  SET_MOVIES_TO_STORE = "SET_MOVIE_TO_STORE",
  SET_ERROR_TO_STORE = "SET_ERROR_TO_STORE",
  SHOW_MOVIE_DETAILS = "SHOW_MOVIE_DETAILS",
  SET_SELECTED_MOVIE_TO_STORE = "SET_SELECTED_MOVIE_TO_STORE",
  FETCH_MOVIE_DETAILS = "FETCH_MOVIE_DETAILS",
  SHOW_FULL_DESCRIPTION = "SHOW_FULL_DESCRIPTION",
  CLEAR_SEARCH = "CLEAR_SEARCH";

export default {
  SET_LOADING,
  ACTION_FAILED,
  UPDATE_SEARCH,
  CLEAR_SEARCH,
  FETCH_MOVIES,
  SET_ERROR_TO_STORE,
  SET_MOVIES_TO_STORE,
  SET_SELECTED_MOVIE_TO_STORE,
  FETCH_MOVIE_DETAILS,
  SHOW_FULL_DESCRIPTION,
  SHOW_MOVIE_DETAILS
};
